name: Flutter Android CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show working directory and files
        run: |
          pwd
          ls -l
      - name: Change to project root
        run: cd ${{ github.workspace }}
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
      - name: Install NDK and CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
          yes | sdkmanager --install "ndk;25.2.9519653"
      - name: Build APK (debug)
        run: |
          cd ${{ github.workspace }}
          flutter build apk --debug
      - name: Build APK (release)
        run: |
          cd ${{ github.workspace }}
          flutter build apk --release
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: build/app/outputs/flutter-apk/*.apk
